//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansalCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Communication
    {
        public int epostaId { get; set; }
        public string E_posta { get; set; }
    }
}
