//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinansalCrm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int invoiceId { get; set; }
        public string invoiceType { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string amount { get; set; }
        public Nullable<int> bankId { get; set; }
    
        public virtual Banks Banks { get; set; }
    }
}
